#!/bin/bash

source .script/incl.sh;

greeting;

read YOUR_CHOICE;

case $YOUR_CHOICE in
     1)
          echo "I want create new"
          ;;
     2)
          echo "I want delete"
          ;;
     *)
          echo "Hmm, wrong number....."
          ;;
esac
exit;