version: '3.4'

services:

    # PHP Configuration
    php:
        container_name: php
        image: iamvincent/php:${PHP_VERSION}-stretch
        build:
            context: ./php/
            args:
                - PHP_LOCAL_VERSION=${PHP_VERSION}
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
            - ./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./php/php.ini/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        networks:
            - local_net

    # Mysql Configuration
    mysql:
        container_name: db_mysql
        image: mysql:5.6
        restart: unless-stopped
        volumes:
            - ./mysql/backup:/var/lib/mysql
            - ./mysql/restore:/docker-entrypoint-initdb.d # restore database
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            local_net:
                ipv4_address: ${MYSQL_IP}

    # Nginx Configuration
    webserver:
        container_name: webserver
        image: iamvincent/nginx:1.17.4-alpine
        build:
            context: ./server/
        depends_on:
            - php
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./server/sites-avaiable.conf:/etc/nginx/conf.d/sites-avaiable.conf
            - ./src:/var/www/html
        networks:
            - local_net

    # PhpMyadmin service
    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql:3306
        ports:
            - 8800:80
        networks:
            - local_net

## Setup a local network using the IP Adress for services
networks:
    local_net:
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_MASK}