version: "3"

services:
    server:
        build: ./server/
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./php/src:/var/www/html
            - ./server/logs:/var/log/nginx
            - ./server/vhost:/etc/nginx/conf.d

    php:
        build:
            context: ./php/
            args:
                - PHP_LOCAL_VERSION=${PHP_VERSION}
        ports:
            - 9000:9000
        volumes:
            - ./php/src:/var/www/html
            - ./php/php.ini/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini

    mysql:
        build: ./mysql/
        restart: always
        volumes:
            - ./mysql/backup:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root