# Before please running `docker network create --subnet=172.28.0.0/16 mylocal`
version: "3.6"

services:

  php:
    build: ./services/php
    container_name: php
    image: vincent:php
    networks:
      - mylocal
    restart: unless-stopped
  
  httpd:
    build: ./services/httpd
    container_name: httpd
    image: vincent:httpd
    networks:
      - mylocal
    restart: unless-stopped

  nginx:
    build: ./services/nginx
    container_name: nginx
    image: vincent:nginx
    networks:
      mylocal:
        ipv4_address: 172.28.0.100
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  mylocal:
    external: true