version: "3.6"

services:

  php:
    build:
      context: ./services/php
      args:
        - PHP_LOCAL_VERSION=${PHP_VERSION}
    container_name: ${PROJECT_NAME}-php
    image: ${REPOSITORY_HUB}/php
    user: "1000:1000"
    networks:
      - public_net
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
  
  httpd:
    build: ./services/httpd
    container_name: ${PROJECT_NAME}-httpd
    image: ${REPOSITORY_HUB}/httpd
    networks:
      - public_net
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
    environment:
      - MY_EMAIL=${MY_EMAIL}
      - PHP_SERVER=${PROJECT_NAME}-php

  nginx:
    build: ./services/nginx
    container_name: ${PROJECT_NAME}-nginx
    image: ${REPOSITORY_HUB}/nginx
    networks:
      public_net:
        ipv4_address: ${NGINX_IP}
    depends_on:
      - httpd
    restart: unless-stopped
    environment:
      - APACHE_SERVER=${PROJECT_NAME}-httpd
    command: sh -c "envsubst '$$APACHE_SERVER' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mysql:
    build: ./services/mysql
    container_name: ${PROJECT_NAME}-mysql
    image: ${REPOSITORY_HUB}/mysql
    networks:
      public_net:
        ipv4_address: ${MYSQL_IP}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: ${PROJECT_NAME}-phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      public_net:
        ipv4_address: ${PHPMYADMIN_IP}
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${PROJECT_NAME}-mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 80:80

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}