# Before please running `docker network create --subnet=172.28.0.0/16 public_net`
version: "3.6"

services:

  php:
    build: ./services/php
    container_name: php
    image: vincent:php
    networks:
      - public_net
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html
  
  httpd:
    build: ./services/httpd
    container_name: httpd
    image: vincent:httpd
    networks:
      - public_net
    depends_on:
      - php
    restart: unless-stopped
    volumes:
      - ./www:/var/www/html

  nginx:
    build: ./services/nginx
    container_name: nginx
    image: vincent:nginx
    networks:
      public_net:
        ipv4_address: 172.28.0.100
    depends_on:
      - httpd
    restart: unless-stopped

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16