version: "3"

services:
    server:
        build: ./server/
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./php/src:/var/www/html
            - ./server/logs:/var/log/nginx
            - ./server/vhost:/etc/nginx/conf.d

    php:
        build: ./php/
        ports:
            - 9000:9000
        volumes:
            - ./php/src:/var/www/html

    mysql:
        