#!/bin/bash

source .script/init.sh;

greeting;

read YOUR_CHOICE;

case $YOUR_CHOICE in
     1)
            create_new_site
            ;;
     2)
          echo "I want delete"
          ;;
     *)
          echo "Hmm, wrong number....."
          ;;
esac
exit;