version: '3.7'

services:

    # PHP Configuration
    php:
        image: iamvincent/php:stretch-7.3
        networks:
            - local_net
        volumes:
            - ./src:/var/www/html
            - ./php/ssmtp.conf:/etc/ssmtp/ssmtp.conf
            - ./php/php.ini/php7.3.ini:/usr/local/etc/php/php.ini

    # Mysql Configuration
    mysql:
        image: mysql:5.6
        networks:
            - local_net
        volumes:
            - ./mysql/backup:/var/lib/mysql
            - ./mysql/restore:/docker-entrypoint-initdb.d # restore database
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root

    # Nginx Configuration
    webserver:
        image: nginx:1.17.4-alpine
        networks:
            - local_net
        depends_on:
            - php
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./server/vhost:/etc/nginx/conf.d
            - ./src:/var/www/html

    # PhpMyadmin service
    pma:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql:3306
        ports:
            - 8800:80
        networks:
            - local_net

## Setup a local network using the IP Adress for services
networks:
    local_net:
        driver: overlay
            